name: Dads'n'Shows
markdown: redcarpet
highlighter: true
permalink: /b/:title
minify_html: false
featured_img: /images/death-from-above-1979.jpg
featured_alt: Death from Above 1979 is back together!!
featured_info: Death from Above 1979 visits DC on 12/1/14.